name: Adobe Commerce - Integration Tests CI Workflow
on:
  workflow_call:
    inputs:
      version:
        description: 'Magento version.'
        required: true
        type: string
      working-directory:
        description: 'Set working directory for your action.'
        required: false
        type: string
      config-path:
        description: 'Path to the phpunit.xml file.'
        required: false
        default: phpunit.xml
        type: string
      test-suites:
        description: 'Test suites to be executed.'
        required: false
        type: string
    secrets:
      composer-auth:
        description: 'Content of auth.json file.'
        required: true

jobs:
  load-integration-tests-config:
    runs-on: ubuntu-latest
    outputs:
      version_config: ${{ steps.load-integration-tests-config.outputs.version_config }}
    steps:
      - name: Load configuration
        id: load-integration-tests-config
        run: |
          config='{
            "versions": [
              {
                "version": "2.4.3",
                "mariadb": "mariadb:10.2",
                "rabbitmq": "rabbitmq:3.8",
                "elasticsearch": "magento/magento-cloud-docker-elasticsearch:7.9-1.3.0",
                "opensearch": ""
              },
              {
                "version": "2.4.6",
                "mariadb": "mariadb:10.2",
                "rabbitmq": "rabbitmq:3.9",
                "elasticsearch": "",
                "opensearch": "magento/magento-cloud-docker-opensearch:2.5-1.3.7"
              },
              {
                "version": "2.4.7",
                "mariadb": "mariadb:10.6",
                "rabbitmq": "rabbitmq:3.13",
                "elasticsearch": "",
                "opensearch": "magento/magento-cloud-docker-opensearch:2.12-1.4.2"
              }
            ]
          }'
          version_config=$(echo $config | jq -c ".versions[] | select(.version == \"${{ inputs.version }}\")")
          echo "version_config=$version_config" >> $GITHUB_OUTPUT

  integration-tests:
    needs: load-integration-tests-config
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vaimo/image-action-magento:${{ inputs.version }}-v1
    services:
      mariadb:
        image: ${{ fromJson(needs.load-integration-tests-config.outputs.version_config).mariadb }}
        env:
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_DATABASE: 'magento_integration_tests'
      elasticsearch:
        image: ${{ fromJson(needs.load-integration-tests-config.outputs.version_config).elasticsearch }}
        env:
          ES_JAVA_OPTS: '-Xms64m -Xmx512m'
      opensearch:
        image: ${{ fromJson(needs.load-integration-tests-config.outputs.version_config).opensearch }}
        env:
          OPENSEARCH_JAVA_OPTS: '-Xms512m -Xmx512m'
          discovery.type: single-node
          plugins.security.disabled: true
      rabbitmq:
        image: ${{ fromJson(needs.load-integration-tests-config.outputs.version_config).rabbitmq }}
    steps:
      - name: Git checkout
        uses: vaimo/action-git-checkout@v1
        with:
          working-directory: ${{inputs.working-directory}}

      - name: Integration Tests action
        uses: vaimo/action-magento-tests@v1
        with:
          composer-auth: ${{ secrets.composer-auth }}
          working-directory: ${{ inputs.working-directory }}
          config-path: ${{ inputs.config-path }}
          test-suites: ${{ inputs.test-suites }}
